const primary = "#1A5F7A";
const primaryLight = "#2E86AB";
const primaryDark = "#0D3F54";
const accent = "#F4D03F";
const accentLight = "#F7DC6F";
const accentDark = "#D4AC0D";

export default {
  light: {
    text: "#1A2C3D",
    textSecondary: "#4A6070",
    textMuted: "#8CA0B0",
    background: "#F0F8FF",
    backgroundSecondary: "#E8F4FD",
    backgroundCard: "#FFFFFF",
    border: "#C8DFF0",
    tint: primary,
    tintLight: primaryLight,
    tintDark: primaryDark,
    accent: accent,
    accentLight: accentLight,
    accentDark: accentDark,
    tabIconDefault: "#8CA0B0",
    tabIconSelected: primary,
    shadow: "rgba(26, 95, 122, 0.12)",
    overlay: "rgba(0,0,0,0.5)",
    success: "#27AE60",
    error: "#E74C3C",
    warning: "#F39C12",
    scannerBorder: primary,
    gold: "#F4D03F",
    starFull: "#F4D03F",
    starEmpty: "#D0E4F0",
  },
  dark: {
    text: "#F0F8FF",
    textSecondary: "#A8C5D8",
    textMuted: "#5A7A90",
    background: "#0B1929",
    backgroundSecondary: "#112233",
    backgroundCard: "#152535",
    border: "#1E3550",
    tint: primaryLight,
    tintLight: "#48A9CC",
    tintDark: primaryDark,
    accent: accent,
    accentLight: accentLight,
    accentDark: accentDark,
    tabIconDefault: "#3A5570",
    tabIconSelected: primaryLight,
    shadow: "rgba(0,0,0,0.4)",
    overlay: "rgba(0,0,0,0.7)",
    success: "#2ECC71",
    error: "#E74C3C",
    warning: "#F39C12",
    scannerBorder: primaryLight,
    gold: "#F4D03F",
    starFull: "#F4D03F",
    starEmpty: "#2A4060",
  },
};
